name: Docker Build - Django

on:
  push:
    paths:
      - 'compose/local/django/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Django Docker Image
        run: |
          docker build -t django-app -f ./compose/local/django/Dockerfile .
          docker push django-app