name: Docker Build - Django

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  ci_django:
    uses: tomctm/devops-coding-challenge/.github/workflows/ci-django.yml@master
  build:
    runs-on: ubuntu-latest
    needs: [ci_django]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Django Docker Image
        run: |
         
          branch_name=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
          
          docker build -t django-app -f ./compose/local/django/Dockerfile .
          docker tag django-app tomctm/django-app:$branch_name          
          docker push tomctm/django-app:$branch_name
        env:
          GITHUB_REF: ${{ github.ref }}